//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordingModule.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbluser
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedTime { get; set; }
        public Nullable<int> IsEdited { get; set; }
        public Nullable<System.DateTime> EditedTime { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> Taskid { get; set; }
    
        public virtual tblTask tblTask { get; set; }
    }
}
